//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseStudent
    {
        public int Id { get; set; }
        public int Reg_Id { get; set; }
        public int Course_Id { get; set; }
        public int Student_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual Student Student { get; set; }
    }
}
